schema_version = "1.0.0"

id = "b_manga_line"
version = "0.3.81"
name = "B-MANGA Line"
tagline = "背面法（反転ハル）によるマンガ風アウトライン"
maintainer = "B-MANGA Project"
type = "add-on"

blender_version_min = "4.3.0"

license = [
    "SPDX:GPL-2.0-or-later",
]

tags = ["Render"]
