schema_version = "1.0.0"

id = "b_name_render"
version = "0.1.23"
name = "B-Name-Render"
tagline = "Command based render presets and fisheye rendering for B-Name workflows"
maintainer = "B-Name Project"
type = "add-on"

blender_version_min = "4.3.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

tags = ["Render"]

permissions = ["files"]
