"""operators — bpy.types.Operator 群."""

from __future__ import annotations

from . import (
    alt_reparent_op,
    asset_op,
    balloon_op,
    balloon_nurbs_tool_op,
    balloon_preset_op,
    balloon_tail_detail_op,
    balloon_tail_op,
    balloon_tail_tool_op,
    balloon_text_curve_op,
    brush_size_op,
    center_point_op,
    data_name_op,
    detail_data_migration_op,
    detail_preset_apply_op,
    detail_preset_management_op,
    raster_detail_action_op,
    detail_transaction_action_op,
    effect_line_op,
    effect_line_object_op,
    effect_line_link_op,
    effect_line_path_op,
    effect_line_preset_op,
    fill_preset_op,
    fill_tool_op,
    folder_op,
    free_transform_op,
    gp_layer_op,
    gpencil_op,
    gradient_preset_op,
    gradient_tool_op,
    image_path_tool_op,
    image_layer_op,
    io_op,
    layer_detail_op,
    layer_link_op,
    layer_link_duplicate_op,
    layer_clipboard_op,
    layer_page_move_op,
    layer_move_op,
    layer_stack_op,
    layer_stack_detail_op,
    mask_object_op,
    mode_op,
    object_tool_op,
    overlay_toggle_op,
    page_file_op,
    page_op,
    page_reorder_drag_op,
    preferences_io_op,
    repair_op,
    coma_edge_move_op,
    coma_edge_style_op,
    coma_edit_op,
    coma_knife_cut_op,
    coma_op,
    coma_create_op,
    coma_camera_op,
    coma_picker,  # noqa: F401 — ヘルパのみ (register 対象外)
    coma_renumber_op,
    coma_split_op,
    coma_vertex_edit_op,
    preset_detail_op,
    preset_op,
    raster_layer_op,
    shortcut_op,
    snap_op,
    spread_op,
    text_auto_ruby_op,
    text_preset_op,
    text_ruby_op,
    text_selection_style_op,
    text_op,
    text_meta_op,
    view_op,
    work_op,
)

_MODULES = (
    work_op,
    detail_data_migration_op,
    page_file_op,
    page_op,
    page_reorder_drag_op,
    spread_op,
    coma_op,
    coma_edit_op,
    coma_camera_op,
    coma_renumber_op,
    coma_split_op,
    coma_vertex_edit_op,
    coma_knife_cut_op,
    coma_create_op,
    coma_edge_move_op,
    coma_edge_style_op,
    snap_op,
    balloon_op,
    balloon_tail_op,
    balloon_tail_detail_op,
    balloon_tail_tool_op,
    balloon_nurbs_tool_op,
    balloon_text_curve_op,
    detail_preset_apply_op,
    detail_preset_management_op,
    raster_detail_action_op,
    detail_transaction_action_op,
    text_auto_ruby_op,
    text_ruby_op,
    text_selection_style_op,
    text_op,
    text_meta_op,
    center_point_op,
    free_transform_op,
    effect_line_op,
    effect_line_object_op,
    effect_line_link_op,
    effect_line_path_op,
    effect_line_preset_op,
    fill_tool_op,
    gradient_tool_op,
    image_path_tool_op,
    folder_op,
    brush_size_op,
    image_layer_op,
    io_op,
    raster_layer_op,
    layer_stack_op,
    layer_stack_detail_op,
    layer_link_op,
    layer_link_duplicate_op,
    layer_clipboard_op,
    layer_page_move_op,
    layer_detail_op,
    layer_move_op,
    mask_object_op,
    object_tool_op,
    overlay_toggle_op,
    alt_reparent_op,
    asset_op,
    repair_op,
    data_name_op,
    mode_op,
    preset_op,
    preset_detail_op,
    text_preset_op,
    balloon_preset_op,
    fill_preset_op,
    gradient_preset_op,
    preferences_io_op,
    gpencil_op,
    gp_layer_op,
    view_op,
    shortcut_op,
)


def register() -> None:
    for module in _MODULES:
        module.register()


def unregister() -> None:
    # 詳細画面の固定対象・同種プリセットロックは、関連Operatorクラスを
    # 解除する前なら開始時状態へ戻せる。復元失敗時もruntime側で全ロックを破棄する。
    try:
        from . import detail_dialog_runtime

        detail_dialog_runtime.cleanup_all_sessions()
    except Exception:
        pass
    for module in reversed(_MODULES):
        try:
            module.unregister()
        except Exception:
            pass
